DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS si;
DROP TABLE IF EXISTS user_si;
DROP TABLE IF EXISTS argue;
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS vote_total;

-- TODO 添加数据库索引配置
-- TODO 将数据重写到SQLAlchemy

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name CHAR(32),
  passwd CHAR(64),
  gender SMALLINT,
  reg TIMESTAMP,
  ban BOOL,
  email VARCHAR(128),
  portrait CHAR(128),
  bio TEXT
);

CREATE TABLE si (
  id BIGSERIAL PRIMARY KEY,
  slug CHAR(64),
  creator BIGINT REFERENCES users (id) ON DELETE CASCADE NULL,
  against BIGINT REFERENCES users (id) ON DELETE CASCADE NULL,
  created TIMESTAMP,
  title VARCHAR(256),
  bio TEXT,
  public BOOL,
  finish BOOL
);

CREATE TABLE user_si (
  uid BIGINT REFERENCES users(id) ON DELETE CASCADE ,
  sid BIGINT REFERENCES si(id) ON DELETE CASCADE,
  dt TIMESTAMP,
  side BOOL
);

CREATE TABLE argue (
  id BIGSERIAL PRIMARY KEY,
  uid BIGINT REFERENCES users(id) ON DELETE CASCADE ,
  sid BIGINT REFERENCES si(id) ON DELETE CASCADE,
  posted TIMESTAMP,
  against BIGINT REFERENCES argue(id) ON DELETE RESTRICT,
  side BOOL,
  content TEXT
);

CREATE TABLE vote (
  uid BIGINT REFERENCES users(id) ON DELETE CASCADE,
  sid BIGINT REFERENCES si(id) ON DELETE CASCADE,
  ts TIMESTAMP,
  support BOOL
);

CREATE TABLE vote_total (
  sid BIGINT PRIMARY KEY REFERENCES si(id) ON DELETE CASCADE,
  a INT,
  b INT
);